name = "cptxt"
main = "src/index.js"
compatibility_date = "2026-05-11"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "COPYTXT_KV"
id = "replace-with-production-kv-namespace-id"
preview_id = "replace-with-preview-kv-namespace-id"
