name = "cptxt"
main = "src/index.js"
compatibility_date = "2026-05-11"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "COPYTXT_KV"
id = "ca2a2541db694d96b92a50178cce7e98"
preview_id = "ca2a2541db694d96b92a50178cce7e98"
